// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:Awdware.Data.Implementation.Repositories.LedRepository.GetAllSettings(System.String)~System.Collections.Generic.IEnumerable{Awdware.Data.Facade.Entities.LedSetting}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:Awdware.Data.Implementation.Repositories.LedRepository.GetAllSettings(System.String)~System.Collections.Generic.IEnumerable{Awdware.Data.Facade.Entities.LedSetting}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:Awdware.Data.Implementation.Repositories.LedRepository.DeleteSetting(System.String,System.Guid)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:Awdware.Data.Implementation.Repositories.LedRepository.DeleteSetting(System.String,System.Guid)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:Awdware.Data.Implementation.Repositories.LedRepository.DeleteLedConfig(System.String,System.Guid)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "<Pending>", Scope = "member", Target = "~M:Awdware.Data.Implementation.Repositories.LedRepository.GetLedConfig(System.String,System.Guid)~Awdware.Data.Facade.Entities.LedEffect")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Design", "CA1062:Validate arguments of public methods", Justification = "EFCore Code", Scope = "namespaceanddescendants", Target = "Awdware.Data.Implementation.Migrations")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:Awdware.Data.Implementation.Repositories.UserRepository.CheckIfEmailExists(System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:Awdware.Data.Implementation.Repositories.UserRepository.CheckIfUsernameExists(System.String)~System.Boolean")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:Awdware.Data.Implementation.Repositories.UserRepository.TryGetUserByEmail(System.String)~Awdware.Data.Facade.Entities.WebUser")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "<Pending>", Scope = "member", Target = "~M:Awdware.Data.Implementation.Repositories.UserRepository.TryGetUserByName(System.String)~Awdware.Data.Facade.Entities.WebUser")]
