# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: contains('["loaderb0t"]', github.actor)
    # The type of runner that the job will run on
    runs-on: deploy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        # Optional, GitHub token, a Personal Access Token with `public_repo` scope if needed
        # Required, if artifact is from a different repo
        # Required, if repo is private a Personal Access Token with `repo` scope is needed
        github_token: ${{secrets.GITHUB_TOKEN}}
        # Required, workflow file name or ID
        workflow: CI
        workflow_conclusion: success
        branch: main
        name: web
        path: artifact-dl
