# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: contains('["loaderb0t"]', github.actor)
    # The type of runner that the job will run on
    runs-on: deploy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: CI
        workflow_conclusion: success
        branch: main
        name: web
        path: artifact-dl
