# This is a basic workflow to help you get started with Actions

name: Deploy

# Controls when the workflow will run
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: contains('["loaderb0t"]', github.actor)
    # The type of runner that the job will run on
    runs-on: deploy

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: 'Download artifact'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            var workflowRuns = await github.actions.listWorkflowRuns({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "ci.yml",
              status: "success",
              branch: "main",
              per_page: 1,
            });
            console.log(`found ${workflowRuns.data.total_count} runs`);
            var workflowRun = workflowRuns.data.workflow_runs[0];
            var runId = workflowRun.id;
            console.log(`found runId ${runId}`);

            var artifacts = await github.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: runId,
            });
            console.log(`found ${artifacts.data.total_count} artifacts`);
            var artifact = artifacts.data.artifacts[0];
            var artifactId = artifact.id;
            console.log(`found artifactId ${artifactId}`);
            var download = await github.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: artifactId,
              archive_format: "zip",
            });
            var fs = require("fs");
            fs.writeFileSync("../web.zip", Buffer.from(download.data));
